COMMANDS = {
    "HELP": "help",
    "HELLO": "hello",
    "CLOSE": "close",
    "EXIT": "exit",
    "ADD_CONTACT": "add",
    "CHANGE_PHONE_OF_CONTACT": "change",
    "FIND_CONTACT_BY_NAME": "contact-by-name",
    "FIND_CONTACT_BY_PHONE": "contact-by-phone",
    "DELETE_PHONE": "delete-phone",
    "DELETE_CONTACT": "delete-contact",
    "SHOW_PHONE": "phone",
    "ALL_CONTACTS": "all-contacts",
    "ADD_BIRTHDAY": "add-birthday",
    "SHOW_BIRTHDAY": "show-birthday",
    "GET_UPCOMING_BIRTHDAYS": "birthdays",
    "GET_BIRTHDAYS_IN_DAYS": "birthdays-in-days",
    "ADD_NOTE": "add-note",
    "ADD_TAGS": "add-tags",
    "FIND_NOTE_BY_TAG": "find-note",
    "EDIT_NOTE_CONTENT": "edit-note",
    "DELETE_NOTE": "delete-note",
    "ALL_NOTES": "all-notes",
    "SHOW_VERSION": "version",
}